[package]
name = "ndless-handler"
description = "Rust handlers for Ndless for TI Nspire"
repository = "https://github.com/lights0123/ndless-rs"
homepage = "https://lights0123.com/ndless-rust/"
license = "MIT OR Apache-2.0"
version = "0.3.0"
authors = ["lights0123 <developer@lights0123.com>"]
edition = "2018"
readme = "README.md"

[dependencies]
ndless = { version = "0.8.6", path = "../ndless" }
ndless-sys = { version = "0.2.0", path = "../ndless-sys" }
cty = "0.2.0"

[features]
default = ["allocator", "oom-handler", "panic-handler", "eh-personality", "lang-start"]
allocator = []
oom-handler = []
panic-handler = []
eh-personality = []
ctype-ptr = []
lang-start = []
